# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services.   # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import alfresco_api
from alfresco_api.models.preference import Preference  # noqa: E501
from alfresco_api.rest import ApiException


class TestPreference(unittest.TestCase):
    """Preference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPreference(self):
        """Test Preference"""
        # FIXME: construct object with mandatory attributes with example values
        # model = alfresco_api.models.preference.Preference()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
