# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services.   # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GroupMembershipBodyCreate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'member_type': 'str'
    }

    attribute_map = {
        'id': 'id',
        'member_type': 'memberType'
    }

    def __init__(self, id=None, member_type=None):  # noqa: E501
        """GroupMembershipBodyCreate - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._member_type = None
        self.discriminator = None
        self.id = id
        self.member_type = member_type

    @property
    def id(self):
        """Gets the id of this GroupMembershipBodyCreate.  # noqa: E501


        :return: The id of this GroupMembershipBodyCreate.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GroupMembershipBodyCreate.


        :param id: The id of this GroupMembershipBodyCreate.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def member_type(self):
        """Gets the member_type of this GroupMembershipBodyCreate.  # noqa: E501


        :return: The member_type of this GroupMembershipBodyCreate.  # noqa: E501
        :rtype: str
        """
        return self._member_type

    @member_type.setter
    def member_type(self, member_type):
        """Sets the member_type of this GroupMembershipBodyCreate.


        :param member_type: The member_type of this GroupMembershipBodyCreate.  # noqa: E501
        :type: str
        """
        if member_type is None:
            raise ValueError("Invalid value for `member_type`, must not be `None`")  # noqa: E501
        allowed_values = ["GROUP", "PERSON"]  # noqa: E501
        if member_type not in allowed_values:
            raise ValueError(
                "Invalid value for `member_type` ({0}), must be one of {1}"  # noqa: E501
                .format(member_type, allowed_values)
            )

        self._member_type = member_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GroupMembershipBodyCreate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GroupMembershipBodyCreate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
